### ISSUE TITLE
arm64 version

### ISSUE THREAD

**Issue by MrJolly** [C0Nd3Mnd/astroneer-docker#3]
Hi, this is more by way of being a request than an issue but would it be possible to build an arm64 version of the container ? This would allow it to be hosted on the free services like AWS and Oracle.

Thanks.

**Comment by C0Nd3Mnd** [comment]
The main hurdle is that the Astroneer dedicated server doesn't natively support ARM (neither does Steam, which is used to download Astroneer inside the image).

It should still be possible using Box64 and Box86. I don't have any experience using Box though, but I have an ARM Mac around so I should be able to look into this. Can't say when though.

**Comment by MrJolly** [comment]
I was assuming Astroneer supported ARM64 ( checking this site [worksonwoa.com](https://www.worksonwoa.com/en/games/astroneer/) ) but I know nothing about docker or Wine so it was more of a wishlist moment.

Thank you for taking the time to reply and fingers crossed for Box64.

**Comment by birdhimself** [comment]
I created a very hacked-together and experimental variant of my image that works with arm64 using box64.

It's tagged as `experimental-arm64`, so your `compose.yml` could look like this:

```yaml
services:
  astroneer:
    image: whalybird/astroneer-server:experimental-arm64
    restart: unless-stopped
    stdin_open: true
    tty: true
    ports:
      - 7777:7777/udp
    volumes:
      - ./saved:/astrotux/AstroneerServer/Astro/Saved
```

I plan to clean my mess up at some point and unify the tags again, but this should at least give you something that works for now (had no issues in my very brief testing on a Hetzner Cloud Ampere ARM box).
